### ISSUE TITLE
A list of ideas for future enhancement. 

### ISSUE THREAD

**Issue by nevadawilliford** [devinstormharris/hurry#2]
1. Passing in an argument when running to specify how long the test will run in seconds.
```
hurry 30  --run for 30 seconds
hurry 60  --run for 1 minute
hurry 180 --run for 3 minutes
```

2. Let the user specify the unit of time with a single letter after the time.
```
hurry 30s
hurry 1m
hurry 3m
```

3. Let the user specify the unit of time with a --unit flag.
```
hurry 30 --unit second
hurry 1 -unit minute
hurry 3 -unit minute
```

4. Keep track of how many mistakes the user made and display those when test is finished. 
5. Add ability to turn on/off error tracking.

**Comment by devinstormharris** [comment]
Thank you for the comments. I've made issues to track these tasks and will be implementing them.
